### PR TITLE
Refactor/testing predictibility

### PR DESCRIPTION
**Pull request by Bert-Proesmans**
Some tests pass/fail sometimes because of certain enchantment effects at game start.
To fix this an additional config option is created to prevent these cards from being automatically added to a deck when FillDecks has been set to true.

This refactor also cleans up static fields/properties to prevent issues with concurrent games.

**This refactor is finalized and pending merge, feedback is appreciated!**

Part of #32

### CODE REVIEW

**Comment by Bert-Proesmans** [comment]
This refactor is ready to be merged.

Static variables are cleaned up where necessary.
Tests shouldn't fail/pass randomly any more because of certain card effects (currently Prince Malchezaar and Choose One cards are excluded when requested)

**Beware:** This is a big refactor that touches a lot of files, make sure to pull from upstream master with a forced rebase. (After this PR is merged of course)
By performing a rebase you'll make sure your local code operates correctly with the other code.

**Comment by rnilva** [comment]
I think implementation of Util.Random should be changed too.
Clones still share the static Random object.  I suggest this one:
https://codeblog.jonskeet.uk/2009/11/04/revisiting-randomness/

**Comment by Bert-Proesmans** [comment]
@rnilva good suggestion and interesting read!
Thread safety is an aspect that isn't being considered in the core at the moment and it's probably not limited to the random source.
I think it might be better in this case to do a separate PR to overhaul all/any thread unsafe instances because pushing the code from this PR is necessary for CI. 
If you want to solve the randomness source problem, please reference issue #45 in the PR.

**Comment by rnilva** [comment]
I appreciate your interest and works!

**Comment by darkfriend77** [comment]
I cherry picked ... :-) thx

**Pull request closed without merging**
