### PR TITLE
show a message box when encounter unhandled exception to avoid app crash

### PR DESCRIPTION
**Pull request by chucklu**
for issue https://github.com/HearthSim/SabberStone/issues/172

### CODE REVIEW

**Comment by chucklu** [comment]
Have no idea why the previous build failed on appveyor, I can pass the unit test on my local.
Just rebase latest  commit on master 
image

**Comment by rnilva** [comment]
The problem is fixed with https://github.com/HearthSim/SabberStone/commit/21b625b9c52c76bdc301e04198d834618366af44

**Comment by chucklu** [comment]
I  got another failed unit test based commit 746a9bf9a30f0affa37413a45
 

> CloneSameSame [FAIL]
>       SabberStoneCore.Exceptions.TaskException : Exception occurs during processing a task.
> Task:[CustomTask][FlagTask], Source:'Voodoo Doll[19]', Target:'Voodoo Doll Cursing[71]'
>       ---- System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.
>       Stack Trace:
>         C:\projects\sabberstone\SabberStoneCore\src\Model\TaskProcessor.cs(244,0): at SabberStoneCore.Model.TaskQueue.Process()
>         C:\projects\sabberstone\SabberStoneCore\src\Model\Game.cs(1154,0): at SabberStoneCore.Model.Game.ProcessTasks()
>         C:\projects\sabberstone\SabberStoneCore\src\Model\Game.cs(1190,0): at SabberStoneCore.Model.Game.DeathProcessingAndAuraUpdate()
>         C:\projects\sabberstone\SabberStoneCore\src\Actions\Attack.cs(76,0): at SabberStoneCore.Actions.Generic.<>c.<get_AttackBlock>b__1_0(Controller c, ICharacter source, ICharacter target, Boolean skipPrePhase, Boolean skipDeathPhase)
>         C:\projects\sabberstone\SabberStoneCore\src\Tasks\PlayerTasks\MinionAttackTask.cs(39,0): at SabberStoneCore.Tasks.PlayerTasks.MinionAttackTask.Process()
>         C:\projects\sabberstone\SabberStoneCore\src\Model\Game.cs(481,0): at SabberStoneCore.Model.Game.Process(PlayerTask gameTask)
>         C:\projects\sabberstone\SabberStoneCoreTest\src\Cloning\CloneStressTest.cs(56,0): at SabberStoneCoreTest.Cloning.CloneStressTest.CloneSameSame()
>         ----- Inner Stack Trace -----
>         C:\projects\sabberstone\SabberStoneCore\src\Model\Entities\EntityData.cs(119,0): at SabberStoneCore.Model.Entities.EntityData.get_Item(GameTag key)
>         C:\projects\sabberstone\SabberStoneCore\src\CardSets\Standard\GilneasCardsGen.cs(2895,0): at SabberStoneCore.CardSets.Standard.GilneasCardsGen.<>c.<NeutralNonCollect>b__19_1(Game g, Controller c, IEntity s, IPlayable t, TaskStack stack)
>         C:\projects\sabberstone\SabberStoneCore\src\Tasks\SimpleTasks\FuncPlayablesTask.cs(54,0): at SabberStoneCore.Tasks.SimpleTasks.CustomTask.Process(Game& game, Controller& controller, IEntity& source, IPlayable& target, TaskStack& stack)
>         C:\projects\sabberstone\SabberStoneCore\src\Tasks\StateTaskList.cs(49,0): at SabberStoneCore.Tasks.StateTaskList.Process(Game& game, Controller& controller, IEntity& source, IPlayable& target, TaskStack& stack)
>            at SabberStoneCore.Tasks.StateTaskList.SabberStoneCore.Tasks.ISimpleTask.Process(Game& game, Controller& controller, IEntity& source, IPlayable& target, TaskStack& stack)
>         C:\projects\sabberstone\SabberStoneCore\src\Model\TaskProcessor.cs(239,0): at SabberStoneCore.Model.TaskQueue.Process()
>   Finished:    SabberStoneCore.Test

**Comment by rnilva** [comment]
Fix for that will be pushed within today. I already fixed it but am also fixing other things together... sorry for the inconvenience.

**Comment by chucklu** [comment]
@rnilva  OK, will you accept this pull request?

**Comment by chucklu** [comment]
Thanks

**Comment by chucklu** [comment]
@rnilva Did you use cherry-pick to do the merge? The fast-forward merge might be a better option.

**Comment by rnilva** [comment]
No, I just used Github's merge button.

**Comment by chucklu** [comment]
Thanks for the confirmation,  I find the github set the [commiter](https://stackoverflow.com/questions/18750808/difference-between-author-and-committer-in-git) as you and keep author as me. And that's why a new commit generated.

**Pull request merged**
